apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
  namespace: app
  labels:
    app: demo
spec:
  # hpaでやる
  #replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        # 生成するPodの名前(任意の名前を付与)を指定
        app: php-apache
    spec:
      containers:
      - image: k8s.gcr.io/hpa-example
        name: php-apache
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
