apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-external-secret
    creationPolicy: Owner
  data:
    - secretKey: ssh_private_key
      remoteRef:
        key: ${git_ssh_private_key}
